source 'https://rubygems.org'

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!

gem 'jekyll', '~> 3.9.0'

gem 'minima' #, '~> 2.0'

group :jekyll_plugins do
  gem 'asciidoctor-diagram'
  gem 'jekyll-asciidoc'
  gem 'jekyll-feed', '~> 0.6'
  gem 'jekyll-seo-tag'
  gem 'jekyll-theme-slate'
  gem 'jekyll-last-modified-at'
  gem 'jekyll-toc'
  gem 'jekyll-sitemap'
end

# Asciidoctor uses pygments for source highlighting
gem 'pygments.rb'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
# Performance-booster for watching directories on Windows
gem 'wdm', '~> 0.1.0' if Gem.win_platform?

# I don't know why we need these
gem 'rexml'
gem 'webrick'
