#!/bin/bash
#
# Build the project for packaging in distribution.
#
# This builds the Mcode that will be used in the distribution. This step is needed
# in order to support p-coding, and maybe other stuff.

mydir=$(dirname "$0")

# Detect Matlab
source "$mydir/locate_matlab.sh"

echo "Building project with Matlab ($matlab)"

"$matlab" -batch "addpath('$mydir'); build_mypackage;"
