#!/bin/bash
#
# Top-level test launcher.
#
# This script fires up a Matlab and runs the tests. Exits with success if all tests
# pass, and with error if any fail.

mydir=$(dirname "$0")


# Detect Matlab
# TODO: Locate Matlab on WSL, and maybe Cygwin

if which matlab &>/dev/null; then
  echo "matlab found on path"
  matlab=matlab
else
  echo "No matlab on path. Detecting Matlab installation..."
  os=$(uname)
  if [[ $os -eq "Darwin" ]]; then
      search_order="${PREFERRED_MATLAB_VERSIONS:-R2021a R2020b R2020a R2019b R2019a R2018b R2018a}"
      for rel in $search_order; do
        app_path="/Applications/MATLAB_${rel}.app"
        echo "Checking $app_path..."
        if [[ -e "$app_path" ]]; then
          matlab="$app_path/bin/matlab"
          break
        fi
      done
  else
    echo >&2 "Error: No matlab on path, and I don't know how to detect it on Linux."
    echo >&2 "Error: Please ensure Matlab is installed, and get it on your \$PATH."
    exit 1
  fi
fi

if [[ -z "$matlab" ]]; then
  echo >&2 "Error: matlab is not on the path and it could not be detected."
fi

echo "Running tests under Matlab ($matlab)"

"$matlab" -batch "addpath('$mydir'); launchtests;"
