#!/bin/bash
#
# Top-level test launcher.
#
# This script fires up a Matlab and runs the tests. Exits with success if all tests
# pass, and with error if any fail.

mydir=$(dirname "$0")

# Detect Matlab
source "$mydir/locate_matlab.sh"

echo "Running tests for mypackage under Matlab ($matlab)"

"$matlab" -batch "addpath('$mydir'); launchtests_mypackage;"
