#!/usr/bin/env bash
#
# This is the script that builds the project documentation into ../doc.
#
# Generally you don't call this directly; instead you run `make doc`.

set -e

mkdir -p ../doc
cp *.html ../doc